---
- name: Install transmission-cli
  pacman: name=transmission-cli state=present

- name: Install transmission-gtk
  pacman: name=transmission-gtk state=present

# Configuration
- name: Make sure transmission is not running
  service:
    name: transmission
    state: stopped
  ignore_errors: true
  tags: transmission

- name: grep and register
  shell: >
    egrep "^{{ transmission.transmission_user }}:" /etc/passwd | awk -F: '{ printf $6 }'
  changed_when: false
  tags: transmission
  register: _user_home

- name: Add downloads folder
  file:
    state: directory
    path: "{{ transmission.transmission_download_dir }}"
    owner: "{{ transmission.transmission_user }}"
    group: "{{ transmission.transmission_group }}"
    mode: 0775
  tags: transmission

- name: Add watch dir
  file:
    state: directory
    path: "{{ transmission.transmission_watch_dir }}"
    owner: "{{ transmission.transmission_user }}"
    group: "{{ transmission.transmission_group }}"
    mode: 0775
  when: transmission.transmission_watch_dir_enabled
  tags: transmission

- name: Add incomplete folder
  file:
    state: directory
    path: "{{ transmission.transmission_incomplete_dir }}"
    owner: "{{ transmission.transmission_user }}"
    group: "{{ transmission.transmission_group }}"
    mode: u=rwX,g=rwX,o=rX
  when: transmission.transmission_incomplete_dir_enabled
  tags: transmission

- name: Add config directory
  file:
    state: directory
    path: "/home/{{ user.name }}/.config/transmission"
    owner: "{{ transmission.transmission_user }}"
    group: "{{ transmission.transmission_group }}"
    mode: u=rwX,g=rwX,o=rX
  tags: transmission

- name: Copy Transmission configuration
  template:
    src: settings.json.j2
    dest: "/home/{{ user.name }}/.config/transmission/settings.json"
    owner: "{{ transmission.transmission_user }}"
    group: "{{ transmission.transmission_group }}"
    mode: u=rwX,g=rwX,o=rX
  tags: transmission

- name: Add user to transmission group
  user: name={{ user.name }} groups={{ transmission.transmission_group }} append=yes
  tags:
    - user
    - transmission
  
- meta: flush_handlers
# Service start
#- name: Start transmission
#  service:
#    name: transmission
#    state: started
#  ignore_errors: true
#  tags: transmission

#- name: Enable transmission
#  service: name=transmission enabled=yes
#  ignore_errors: true
