---
- name: Install transmission-cli
  pacman: name=transmission-cli state=present

- name: Install transmission-gtk
  pacman: name=transmission-gtk state=present

# Configuration
- name: Make sure transmission is not running
  service:
    name: transmission
    state: stopped
  ignore_errors: true
  tags: transmission

- name: grep and register
  shell: >
    egrep "^{{ transmission_user }}:" /etc/passwd | awk -F: '{ printf $6 }'
  changed_when: false
  tags: transmission
  register: _user_home

- name: Add downloads folder
  file:
    state: directory
    path: "{{ transmission_download_dir }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0775
  tags: transmission

- name: Add watch dir
  file:
    state: directory
    path: "{{ transmission_watch_dir }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0775
  when: transmission_watch_dir_enabled
  tags: transmission

- name: Add incomplete folder
  file:
    state: directory
    path: "{{ transmission_incomplete_dir }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0775
  when: transmission_incomplete_dir_enabled
  tags: transmission

- name: Add config directory
  file:
    state: directory
    path: "{{ _user_home.stdout }}/.config/transmission"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0755
  tags: transmission

- name: Copy Transmission configuration
  template:
    src: settings.json.j2
    dest: "{{ _user_home.stdout }}/.config/transmission/settings.json"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
  tags: transmission

- name: Add current user to transmission group
  user:
    name: "{{ transmission_user }}"
    groups: "{{ transmission_group }}"
    append: yes
  tags: transmission

- meta: flush_handlers

# Service start
- name: Start transmission
  service:
    name: transmission
    state: started
  ignore_errors: true
  tags: transmission

- name: Enable transmission
  service: name=transmission enabled=yes
  ignore_errors: true
