---
- name: Install w3m
  pacman: name=w3m state=present

- name: Install Firefox
  pacman: name=firefox state=present
  tags:
    - firefox
    
#- name: Install Firefox addons - adnauseam
#  firefox_addon:
#    url: https://addons.mozilla.org/en-US/firefox/addon/adnauseam/
#    state: present
#  tags:
#   - firefox

#- name: Install Firefox addons - httpseverywhere
#  firefox_addon:
#    url: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/
#    state: present
#  tags:
#   - firefox
        
#- name: Install Firefox addons - lastpass
#  firefox_addon:
#    url: https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/
#    state: present
#  tags:
#   - firefox
   
#- name: Install Firefox addons - privacybadger
#  firefox_addon:
#    url: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/
#    state: present
#  tags:
#   - firefox

- name: Jail Firefox
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/firefox
        state=link
  tags:
    - firefox
    - firejail

- name: Verify Firefox firejail local profile exists
  file: path=/etc/firejail/firefox.local state=touch
  tags:
    - firefox
    - firejail

- name: Restrict Firefox access to /etc
  lineinfile:
    dest: /etc/firejail/firefox.local
    regexp: "^private-etc"
    line: "private-etc firejail,passwd,group,hostname,hosts,nsswitch.conf,resolv.conf,gtk-2.0,gtk-3.0,fonts,mime.types,asound.conf,pulse,localtime"
  tags:
    - firefox
    - firejail

- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Jail Chromium
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/chromium
        state=link
  tags:
    - chromium
    - firejail

- name: Verify Chromium firejail local profile exists
  file: path=/etc/firejail/chromium.local state=touch
  tags:
    - chromium
    - firejail

- name: Restrict Chromium access to /etc
  lineinfile:
    dest: /etc/firejail/chromium.local
    regexp: "^private-etc"
    line: "private-etc firejail,passwd,group,hostname,hosts,nsswitch.conf,resolv.conf,gtk-2.0,gtk-3.0,fonts,mime.types,asound.conf,pulse,localtime"
  tags:
    - chromium
    - firejail

- name: Install Pepper Flash
  pacman: name=pepper-flash state=present
  tags:
    - chromium

- name: Install tor-browser-en
  aur: name=tor-browser-en user={{ user.name }} skip_pgp=yes
  tags:
    - tor-browser
    - aur

- name: Jail tor-browser-en
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/tor-browser-en
        state=link
  tags:
    - tor-browser
    - firejail
