---
- name: Install w3m
  pacman: name=w3m state=present

- name: Install Firefox
  pacman: name=firefox state=present
  tags:
    - firefox

- name: Install python2-pip
  pacman: name=python2-pip state=present
  tags:
    - python

- name: install role requirements
  pip: name={{ item }} state=present
  with_items:
    - xmltodict
    - requests
  tags:
    - python
    - firefox

- name: create profiles
  firefox_profile:
    name: "{{ item.name }}"
    state: present
  become: no
  with_items: "{{ firefox_profiles }}"
  register: profiles
  tags:
    - firefox

- name: install extensions
  firefox_addon:
    name: "{{ item.1 }}"
    state: present
    profile: "{{ item.0.name }}"
  become: no
  with_subelements:
    - "{{ firefox_profiles }}"
    - extensions
  tags:
    - firefox

- name: set preferences
  template:
    src: templates/user.js.j2
    dest: "{{item.profile_path }}/user.js"
  with_items: "{{ profiles.results }}"
  when: firefox_preferences or firefox_profile_preferences[item.profile_name] is defined
  become: no
  tags:
    - firefox

- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Install Pepper Flash
  pacman: name=pepper-flash state=present
  tags:
    - chromium

- name: Install tor-browser-en
  aur: name=tor-browser-en user={{ user.name }} skip_pgp=yes
  tags:
    - tor-browser
    - aur
  ignore_errors: yes
