---
- name: Install Bash
  pacman: name={{ item }} state=present
  with_items:
    - bash
    - bash-completion
  tags:
    - shell

- name: Install ZSH
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
  tags:
    - shell

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success
  sudo: no